name = "hono-app"
main = "src/worker.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
AUTH0_DOMAIN = "new-corp.us.auth0.com"
AUTH0_CLIENT_ID = "WVEjIaqjBnkBJ9ScDaeVRa10Lh2ErZxH"
APP_BASE_URL = "https://hono-app.your-subdomain.workers.dev"
